
import { GoogleGenAI, Type } from "@google/genai";

export interface GroundingChunk {
  web?: {
    uri: string;
    title: string;
  };
  maps?: {
    uri: string;
    title: string;
  };
}

export interface ChatMessage {
  role: 'user' | 'model';
  parts: { text: string }[];
}

export const summarizeMeeting = async (transcript: string[]) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Please summarize the following meeting transcript and extract key decisions and action items in JSON format: \n\n ${transcript.join('\n')}`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            summary: { type: Type.STRING },
            decisions: { type: Type.ARRAY, items: { type: Type.STRING } },
            actionItems: { 
              type: Type.ARRAY, 
              items: { 
                type: Type.OBJECT, 
                properties: {
                  owner: { type: Type.STRING },
                  task: { type: Type.STRING },
                  dueDate: { type: Type.STRING }
                }
              }
            }
          }
        }
      }
    });
    return JSON.parse(response.text);
  } catch (error) {
    console.error("Summary Error:", error);
    return null;
  }
};

export const getWisdomSearch = async (userPrompt: string) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: userPrompt,
      config: {
        tools: [{ googleSearch: {} }],
        systemInstruction: "You are the Conscious Network Hub Wisdom Node. Use Google Search to provide accurate, up-to-date information about decentralization, blockchain ethics, and social learning trends.",
        temperature: 0.7,
      },
    });

    const text = response.text;
    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks as GroundingChunk[] | undefined;
    
    return { text, groundingChunks };
  } catch (error: any) {
    console.error("Search Error:", error);
    return { text: "Search layer temporarily offline.", groundingChunks: [] };
  }
};

export const getWisdomMaps = async (userPrompt: string, location?: { latitude: number, longitude: number }) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: userPrompt,
      config: {
        tools: [{ googleMaps: {} }],
        toolConfig: {
          retrievalConfig: {
            latLng: location || { latitude: 37.7749, longitude: -122.4194 } 
          }
        },
        systemInstruction: "You are the Wisdom Node specializing in geographic and place-based information for the Conscious Network Hub. Use Google Maps to find restaurants, centers, or locations.",
      },
    });

    const text = response.text;
    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks as GroundingChunk[] | undefined;
    
    return { text, groundingChunks };
  } catch (error) {
    console.error("Maps Error:", error);
    return { text: "Maps layer temporarily offline.", groundingChunks: [] };
  }
};

export const fastWisdomChat = async (message: string, systemContext?: string) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: message,
      config: {
        systemInstruction: systemContext || "You are the Fast Wisdom Node of the Conscious Network Hub. Provide quick, concise, and futuristic guidance on the platform and its ethical frameworks.",
      },
    });
    return response.text;
  } catch (error) {
    console.error("Fast Chat Error:", error);
    return "Neural link lag detected.";
  }
};

export const generateWisdomImage = async (prompt: string, aspectRatio: string = "1:1") => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: { parts: [{ text: prompt }] },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as any,
          imageSize: "1K"
        }
      },
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    return null;
  } catch (error: any) {
    console.error("Image Gen Error:", error);
    return null;
  }
};

// Daily autogenerated wisdom on AI, blockchain, spirituality, and consciousness
export const getDailyWisdom = async () => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const today = new Date().toLocaleDateString();
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Generate a brief, insightful daily wisdom message for ${today} that combines perspectives on:
        1. AI ethics and consciousness
        2. Blockchain and decentralization
        3. Spirituality and personal development
        4. Religious and philosophical teachings
        5. How these topics relate to collective human wellness
        
        Keep it to 2-3 sentences, inspirational yet grounded in practical wisdom. Format as a coherent flowing message.`,
      config: {
        tools: [{ googleSearch: {} }],
        systemInstruction: "You are the Conscious Network Hub Daily Wisdom Generator. Create authentic, multidisciplinary insights that honor AI ethics, blockchain technology, spiritual development, and collective consciousness.",
        temperature: 0.8,
      },
    });

    const text = response.text;
    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks as GroundingChunk[] | undefined;
    
    return { text, groundingChunks };
  } catch (error: any) {
    console.error("Daily Wisdom Error:", error);
    return { 
      text: "The consciousness stream flows through interconnected networks of knowledge and purpose. Today, we align our intentions with ethical technology and collective wellbeing.",
      groundingChunks: [] 
    };
  }
};

// Q&A service for platform knowledge and wellness
export const askEthicalAI = async (question: string, context?: { category?: 'platform' | 'wellness' | 'general' }) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    let systemContext = "You are the Conscious Network Hub Ethical AI Assistant. You provide knowledgeable, compassionate responses about:";
    
    if (context?.category === 'platform') {
      systemContext += "\n- Higher Conscious Network LLC mission and vision\n- Conscious Network Hub platform features and capabilities\n- Decentralized identity and data sovereignty\n- Provider and community engagement";
    } else if (context?.category === 'wellness') {
      systemContext += "\n- Mental wellness and emotional health\n- Spiritual development and consciousness\n- Learning pathways and course topics\n- Personal growth and alignment practices";
    } else {
      systemContext += "\n- Platform information and wellness topics\n- AI ethics and decentralization\n- Blockchain and sovereignty\n- Spiritual and educational insights";
    }
    
    systemContext += "\n\nAlways be helpful, honest, and grounded in the platform's mission of ethical technology and human autonomy.";

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: question,
      config: {
        tools: [{ googleSearch: {} }],
        systemInstruction: systemContext,
        temperature: 0.7,
      },
    });

    const text = response.text;
    const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks as GroundingChunk[] | undefined;
    
    return { text, groundingChunks };
  } catch (error: any) {
    console.error("Ethical AI Error:", error);
    return { 
      text: "I'm experiencing a temporary connection lag. Please try your question again in a moment, or contact support for immediate assistance.",
      groundingChunks: [] 
    };
  }
};

// Process platform issue reports with AI direction
export const processPlatformIssue = async (issue: { title: string; description: string; category: string; userEmail?: string }) => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Platform Issue Report:
        Title: ${issue.title}
        Category: ${issue.category}
        Description: ${issue.description}
        
        Please provide:
        1. A brief acknowledgment of the issue
        2. Initial assessment of severity and impact
        3. Recommended next steps for resolution
        4. A support ticket priority level (Low, Medium, High, Critical)
        5. Estimated resolution direction`,
      config: {
        systemInstruction: "You are the Conscious Network Hub Support AI. Analyze platform issues with empathy and technical understanding. Provide clear guidance for resolution while maintaining the platform's ethical standards.",
      },
    });

    return {
      analysis: response.text,
      timestamp: new Date().toISOString(),
      status: 'acknowledged'
    };
  } catch (error: any) {
    console.error("Issue Processing Error:", error);
    return {
      analysis: "Your issue has been received and logged. Our support team will review it shortly.",
      timestamp: new Date().toISOString(),
      status: 'logged'
    };
  }
};
